"""add agent_type and model_used

Revision ID: 63d02157e221
Revises: 97477f3ec488
Create Date: 2026-02-16 14:32:31.016885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63d02157e221'
down_revision: Union[str, Sequence[str], None] = '97477f3ec488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('agent_type', sa.String(length=50), server_default='specialist', nullable=False))
    op.add_column('analyses', sa.Column('model_used', sa.String(length=100), server_default='qwen2.5:7b', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'model_used')
    op.drop_column('analyses', 'agent_type')
    # ### end Alembic commands ###
